config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  resources :restaurants do
    resources :reviews, only: [ :create, :destroy]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    flash[:confirmation] = "Your restaurant was created"
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    flash[:confirmation] = "Your restaurant was updated"
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:confirmation] = "Your restaurant was deleted"
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

 def create
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review = @restaurant.reviews.create(review_params)
  redirect_to restaurant_path(@restaurant)
 end

 def destroy
  @restaurant = Restaurant.find(params[:restaurant_id])
  d = @restaurant.reviews.find(params[:id])
  d.destroy
  redirect_to restaurant_path(@restaurant)
 end

 private
  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

<p><%= link_to 'Back', restaurant_path(@restaurant) %></p>

app/views/restaurants/index.html.erb
<div class="text-center">
  <h1>Restaurant's list</h1>

  <%= link_to 'Create a new restaurant', new_restaurant_path, class: "btn btn-default" %>

</br> </br> </br>

  <p><%= flash[:confirmation] %></p>

  <ul class="list-unstyled"><% @restaurants.each do |restaurant| %>
    <li><h3><%= restaurant.name %></h3>
        <h4>Located at: <%= restaurant.address %></h4>

        <%= link_to restaurant_path(restaurant) do %>
          <button type="button" class="btn btn-primary">Show more details</button>
        <% end %>
    </li>
    <% end %>
  </ul>

</div>

app/views/restaurants/new.html.erb
<%= render 'form' %>

<p><%= link_to 'Back', restaurants_path %></p>

app/views/restaurants/show.html.erb
</br>

<div class="text-center">
  <h1><%= @restaurant.name %></h1>

  </br></br>

  <h4>Adress : <%= @restaurant.address %></h4>
  <h4>Phone : <%= @restaurant.phone %></h4>
  <h4>Category :<%= @restaurant.category %></h4>

  </br></br>

  <%= link_to restaurants_path do %>
    <button type="button" class="btn btn-primary">Back</button>
  <% end %>
  <%= link_to edit_restaurant_path(@restaurant) do %>
    <button type="button" class="btn btn-warning">Edit</button>
  <% end %>
  <%= link_to restaurant_path, method: 'delete' do %>
    <button type="button" class="btn btn-danger">Delete</button>
  <% end %>

  </br></br>

  <h2>Comments</h2>

  <button class="btn btn-default" data-toggle="modal" data-target="#myModal">
    Add a new comment
  </button>


  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
        </div>
        <div class="modal-body">
          <%= form_for([@restaurant, @review]) do |f| %>
              <p><%= f.label :content %>
              <%= f.text_field :content %></p>

            <p><%= f.label :rating %>
            <%= f.text_field :rating %></p>

            <%= f.submit %></p>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


  <% @restaurant = Restaurant.find(params[:id]) %>
  <ul class="list-unstyled"><% @restaurant.reviews.each do |review| %>
    <li><h4>Comment: <%= review.content %></h4>
        <h4>Rate: <%= review.rating %></h4>

        <%= link_to restaurant_review_path(@restaurant, review), method: 'delete' do %>
          <button type="button" class="btn btn-danger">Delete</button>
        <% end %>
    </li>
    <% end %>
  </ul>

</div>